blog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'blog'
urlpatterns = [
	#path('', views.post_list, name='post_list'),
	
	url(r'^$', views.post_list, name='post_list'),
	url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
	url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
	url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=200, unique = True, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
            # Uncomment if you don't want the slug to change every time the name changes
            #if self.id is None:
                    #self.slug = slugify(self.name)
            self.slug = slugify(self.name)
            super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
	question_text=models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <=now

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE) #Becomes question_id
	choice_text=  models.CharField(max_length = 200)
	votes = models.IntegerField(default=0)

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('title', 'text')

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post, Category
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from .forms import PostForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user
from django.http import HttpResponse, Http404


def post_list(request):
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
	if request.method =="POST":
		form = PostForm(request.POST)
		if form.is_valid():
		    post = form.save(commit=False)
		    post.author = request.user
		    post.published_date = timezone.now()
		    post.save()
		    return redirect('blog:post_detail', pk=post.pk)

	else:
		form = PostForm()
	return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    poster = request.user

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
        	if post.author != request.user:
        		raise Http404("You are not allowed to edit this post.")

        	else:
	            post = form.save(commit=False)
	            #post.author = poster
	            post.published_date = timezone.now()
	            post.save()
	            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

def category(request, category_name_slug):
	context_dict = {}
	category = get_object_or_404(Category, slug=category_name_slug)
	context_dict['category_name'] = category.name

	post = Post.objects.filter(category=category)
	#post = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	context_dict['post'] = post
	context_dict['category'] = category

	return render(request, 'blog/category.html', context_dict)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Question, Choice
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone





class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
    	return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {'question': question, 'error_message' :"You didn't select a choice.", })

	else:
		selected_choice.votes +=1
		selected_choice.save()		
	return HttpResponseRedirect(reverse('polls:results', args = (question.id,)))
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'



    def get_queryset(self):
				    return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]





'''
def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	template = loader.get_template('polls/index.html')
	context= {
		'latest_question_list': latest_question_list
	}
	return render(request, 'polls/index.html', context)

def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/detail.html', {'question': question})


	#return HttpResponse("You're looking at question %s." % question_id)


def results(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/results.html', {'question': question})	
'''

blog/templates/blog/base.html
{% load staticfiles %}

<html>


    <div class="topnav">
      <a href="/">Home</a>
      <a href="/post_list/">News</a>
      <a href="#">Opinion</a>
      <a href="#">Contact</a>
    </div>

<div class = "main">

    <head>
        <title>Django d blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
       
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>




    <body>
        <div class="page-header">
            <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="/">Django Girls Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                  
                {% endblock %}
                <a href="http://127.0.0.1:8000/polls/">Link to polls</a>
                   {% if user.is_authenticated %}
                     <li>User: {{ user.get_username }}</li>
                     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
                   {% else %}
                     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
                   {% endif %} 




                </div>
            </div>
        </div>
    </body>
</div>
</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}

{% block content %}
	<body>
		hellooooo
        {% if category %}

        <h1>{{ category_name }}</h1>
            {% if post %}
            ifpost
            <ul>
                {% for post in post %}
                postname
                {{post.name}}}
                <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                {% endfor %}
            </ul>
            {% else %}
                <strong>No pages currently in category.</strong>
            {% endif %}
        {% else %}
            The specified category {{ category_name }} does not exist!
        {% endif %}
    </body>






{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}

        {% if post.author == request.user %}
            <h1>{{ post.title }}</h1>
            <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}

        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
        <p>Written by: {{post.author}}</p>
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
            <p>Author {{post.author}}</p>

        </div>
    {% endfor %}




     {% if categories %}
            <ul>
                {% for category in categories %}
                <li>{{ category.name }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}

{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type = "text/css" href={%static 'polls/style.css' %}">


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}"> {{question.question_text}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>